export const baseUrl = "https://whpapi.transpost.co/api";
// export const baseUrl = "http://127.0.0.1:8000/api";
export const baseUrl2 = "http://164.92.120.19/api";
// export const baseUrl="http://127.0.0.1:8001/api"
export const graphqlbaseUrl =
  "https://monkfish-app-9plxl.ondigitalocean.app/graphql";
export const graphqlProductUrl = "https://seashell-app-kswll.ondigitalocean.app/graphql";
// export const graphqlProductUrl = "https://seashell-prod-app-rigzk.ondigitalocean.app/graphql";
export const graphqlProductionUrl = "https://seashell-prod-app-rigzk.ondigitalocean.app/graphql";
export const getAllReels="/getAllReels"
export const signup = "/signup";
export const login = "/login";
export const addCart = "/cart/sync";
export const removeCart = "/cart/sync";
export const cartUpdate = "/cart/sync";
export const syncCart = "/cart/sync";
export const addAddress = "/customer/address";
export const coupon = "/coupon";
export const updateProfile = "/customer/details";
export const customerDetails = "/customer/getCustomer";
export const gms = "/gms/store";
export const addwishlist = "/addOrUpdateProductWishlist";
export const removewishlist = "/removeProductWishlist";
export const order = "/orders";
export const category = "/getAllParentCategories";
export const contactForm = "/queries/store";
export const storeReviews = "/storeReview";
export const blogs = "/blogs";
export const voucher = "/voucher";
export const getProductbyId = "/products/";
export const getProducts = "/getall-products";
export const getCartItems = "/cart";
export const getAddress = "/customer/getAddresses";
export const getwishlisted = "/wishlist";
export const getOrders = "/getOrders";
export const getAllBanners = "/getAllBanners";
export const getSubBanners = "/getAllSubbanner";
export const userTracking = "/user-tracking";
