interface Variation {
    color: string;
    colorCode: string;
    colorImage: string;
    image: string;
}
export interface ImageDetails{
    image_path:string|null,
    order:string,
    alt_text?:string|null,
}
export interface VideoDetails{
    video_path:string|null,
    order:number|string,
    alt_text?:string|null,
}

export interface ProductType {
    productId: number,
    SKU?:string|number,
    variantId?:number|null,
    title?:string,
    displayTitle?:string,
    shortDesc?:string,
    longDesc?:string,
    url?:string,
    tags?:string[]|null,
    collectionName?:string|null,
    shopFor?:string[]|null,
    occasion?:string|null,
    theme?:string|null,
    length?:string|null,
    breadth?:string|null,
    height?:string|null,
    weightRange?:string|null,
    addDate?:string|null,
    lastModificationDate?:string|null,
    created_at?:string|null,
    updated_at?:string|null,
    sizeId?:number|null,
    productSize?:string|null,
    productQty?:number|null,
    attributedId?:number|null,
    preSalesProductQueries?:string|null,
    isReplaceable?:number|null,
    isReturnable?:number|null,
    isInternationalShippingAvailable?:number|null,
    customizationAvailability?:number|null,
    fastDelivery?:number|null,
    tryAtHome?:number|null,
    isActive?:number|null,
    grossWeight?:number|null,
    netWeight?:number|null,
    productAttributes?:string[]|null,
    discountId?:number|null,
    discountCategory?:string|null,
    discountActive?:number|null,
    typeOfDiscount?:string|null,
    discountValue?:string|null,
    discountAmount?:string|null,
    discountPrice?:string|null,
    offerStartDate?:string|null,
    offerEndDate?:string|null,
    mediaId?:string|null,
    imageDetails?:ImageDetails[]|null,
    videoDetails?:VideoDetails[]|null,
    materialId?:number|null,
    metalType?:string|null,
    metalPurity?:string|null,
    metalWeight?:string|null,
    makingType?:string|null,
    makingChargesPerGrams?:string|null,
    additionalCost?:string|null,
    productPrice?:string|null,
    stoneDetails?:string[]|null,
    diamondDetails?:string[]|null,
}